apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  namespace: default
  labels:
    app: testapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp2
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      containers:
      - name: testapp2
        image: ozkanpoyrazoglu/ozkantestapp2:%buildnumber%
        ports:
        - containerPort: 8080
          protocol: TCP