apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment-%buildnum%
  namespace: %namespace%
  labels:
    app: testapp
    role: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
      role: blue
  template:
    metadata:
      labels:
        app: testapp
        role: blue
    spec:
      containers:
      - name: testapp
        image: ozkanpoyrazoglu/ozkantestapp2:%buildnumber%
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:      
      maxSurge: 50%

