apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  namespace: %namespace%
  labels:
    app: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: ozkanpoyrazoglu/ozkantestapp2:%buildnumber%
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 8080
  strategy:
    type: RollingUpdate


