apiVersion: v1
kind: Service
metadata:
  labels:
    app: testapp
    role: deploy_%buildnum%
  name: testapp-deployment
  namespace: testapp
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: testapp
    role: deploy_%buildnum%
  sessionAffinity: None
  type: ClusterIP
